version: "3"

services:
  db:
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    user: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=denden_lab_vote.settings.prod
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'denden-lab-vote.tk -> http://nginx:8080'
      STAGE: 'production'
    depends_on:
      - nginx
    volumes:
      - /var/lib/ssl_certs:/var/lib/https-portal
  nginx:
    image: nginx:latest
    volumes:
      - ./staticfiles:/staticfiles
      - ./media:/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8080:8080
    depends_on:
      - web