version: "3"

services:
  db:
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    user: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    volumes:
      - ./staticfiles:/staticfiles
      - ./media:/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web
