# Generated by Django 4.0.1 on 2022-01-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote_site", "0002_alter_user_vote1_alter_user_vote2_alter_user_vote3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="year",
            field=models.IntegerField(
                choices=[(2022, 2022), (2023, 2023), (2024, 2024)], default=2022
            ),
        ),
    ]
