# Generated by Django 4.0.1 on 2022-02-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote_site", "0004_alter_user_vote1_alter_user_vote2_alter_user_vote3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="belongs_to",
            field=models.CharField(
                choices=[
                    ("Engineering", "工学研究科"),
                    ("Informatics", "情報学研究科"),
                    ("Energy", "エネルギー科学研究科"),
                    ("Humanosphere", "生存圏研究所"),
                    ("Advanced Energy", "エネルギー理工学研究所"),
                    ("Media", "学術情報メディアセンター"),
                ],
                max_length=20,
            ),
        ),
    ]
