# Generated by Django 4.0.1 on 2022-02-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote_site", "0005_alter_lab_belongs_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[(2022, 2022), (2023, 2023), (2024, 2024)], default=2022
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                (
                    "vote1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote1",
                        to="vote_site.lab",
                    ),
                ),
                (
                    "vote2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote2",
                        to="vote_site.lab",
                    ),
                ),
                (
                    "vote3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote3",
                        to="vote_site.lab",
                    ),
                ),
                (
                    "vote4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote4",
                        to="vote_site.lab",
                    ),
                ),
                (
                    "vote5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote5",
                        to="vote_site.lab",
                    ),
                ),
                (
                    "vote6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote6",
                        to="vote_site.lab",
                    ),
                ),
                (
                    "vote7",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote7",
                        to="vote_site.lab",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
