# Generated by Django 4.0.1 on 2022-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote_site", "0006_vote_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
